Repository ManageIQ/rbvmomi2, pull requests merged in 2024-01, with the labels that each got.

#45 Fix issue where tests interpreted 3.0 as 3 which is ruby-3-latest (3.3)
  .github/workflows/test.yml
Labels: bug, test

#43 Add Ruby 3.2 to test matrix
  .github/workflows/test.yml
Labels: test

#42 Drop Issue/PR templates after merge of ManageIQ/.github#7
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: technical debt

#48 Add a .github/CODEOWNERS file
  .github/CODEOWNERS
Labels: developer

#44 Drop CONTRIBUTORS.md
  CONTRIBUTORS.md
  README.md
  Rakefile
Labels: documentation, technical debt
